services:
  - type: web
    name: pokedex-vue
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    env:
      - key: NODE_ENV
        value: production
    routes:
      - source: /
        destination: /dist/index.html
